[package]
name = "sabikui-algs"
version = "0.0.0"
description = "A hash algorithm executable generator for sabikui"

repository.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
blake2 = "0.10.6"
ascon-hash = "0.3.1"
belt-hash = "0.1.1"
fsb = "0.1.3"
gost94 = "0.10.4"
groestl = "0.10.1"
jh = "0.1.0"
md2 = "0.10.2"
md4 = "0.10.2"
ripemd = "0.1.3"
sha2 = "0.10.9"
sha3 = "0.10.8"
shabal = "0.4.1"
sm3 = "0.4.2"
streebog = "0.10.2"
tiger = "0.2.1"
whirlpool = "0.10.4"

# Ascon-Hash
[[bin]]
name = "ascon"
path = "src/bin/ascon.rs"

# Belt-Hash
[[bin]]
name = "belt"
path = "src/bin/belt.rs"

# Blake2 Family
[[bin]]
name = "blake2s256"
path = "src/bin/blake2/blake2s256.rs"

[[bin]]
name = "blake2b512"
path = "src/bin/blake2/blake2b512.rs"

# FSB Family
[[bin]]
name = "fsb-160"
path = "src/bin/fsb/fsb160.rs"

[[bin]]
name = "fsb-224"
path = "src/bin/fsb/fsb224.rs"

[[bin]]
name = "fsb-256"
path = "src/bin/fsb/fsb256.rs"

[[bin]]
name = "fsb-384"
path = "src/bin/fsb/fsb384.rs"

[[bin]]
name = "fsb-512"
path = "src/bin/fsb/fsb512.rs"

# GOST94
[[bin]]
name = "gost94"
path = "src/bin/gost94.rs"

# Grøst Family
[[bin]]
name = "groestl-224"
path = "src/bin/groestl/groestl224.rs"

[[bin]]
name = "groestl-256"
path = "src/bin/groestl/groestl256.rs"

[[bin]]
name = "groestl-384"
path = "src/bin/groestl/groestl384.rs"

[[bin]]
name = "groestl-512"
path = "src/bin/groestl/groestl512.rs"

# JH Family
[[bin]]
name = "jh-224"
path = "src/bin/jh/jh224.rs"

[[bin]]
name = "jh-256"
path = "src/bin/jh/jh256.rs"

[[bin]]
name = "jh-384"
path = "src/bin/jh/jh384.rs"

[[bin]]
name = "jh-512"
path = "src/bin/jh/jh512.rs"


# MD2
[[bin]]
name = "md2"
path = "src/bin/md2.rs"

# MD4
[[bin]]
name = "md4"
path = "src/bin/md4.rs"

# MD5
[[bin]]
name = "md5"
path = "src/bin/md5.rs"

# RIPEMD Family
[[bin]]
name = "ripemd-128"
path = "src/bin/ripemd/ripemd128.rs"

[[bin]]
name = "ripemd-160"
path = "src/bin/ripemd/ripemd160.rs"

[[bin]]
name = "ripemd-256"
path = "src/bin/ripemd/ripemd256.rs"

[[bin]]
name = "ripemd-320"
path = "src/bin/ripemd/ripemd320.rs"

# SHA1
[[bin]]
name = "sha1"
path = "src/bin/sha1.rs"

# SHA2 Family
[[bin]]
name = "sha-224"
path = "src/bin/sha2/sha224.rs"

[[bin]]
name = "sha-256"
path = "src/bin/sha2/sha256.rs"

[[bin]]
name = "sha-384"
path = "src/bin/sha2/sha384.rs"

[[bin]]
name = "sha-512"
path = "src/bin/sha2/sha512.rs"

[[bin]]
name = "sha-512_224"
path = "src/bin/sha2/sha512_224.rs"

[[bin]]
name = "sha-512_256"
path = "src/bin/sha2/sha512_256.rs"


[[bin]]
name = "sha3-256"
path = "src/bin/sha3-256.rs"

[[bin]]
name = "sha3-512"

# Shabal Family
[[bin]]
name = "shabal-192"
path = "src/bin/shabal/shabal192.rs"

[[bin]]
name = "shabal-224"
path = "src/bin/shabal/shabal224.rs"

[[bin]]
name = "shabal-256"
path = "src/bin/shabal/shabal256.rs"

[[bin]]
name = "shabal-384"
path = "src/bin/shabal/shabal384.rs"

[[bin]]
name = "shabal-512"
path = "src/bin/shabal/shabal512.rs"

# Streebog Family
[[bin]]
name = "streebog-256"
path = "src/bin/streebog/streebog256.rs"

[[bin]]
name = "streebog-512"
path = "src/bin/streebog/streebog512.rs"

# SM3
[[bin]]
name = "sm3"
path = "src/bin/sm3.rs"

# Tiger
[[bin]]
name = "tiger"
path = "src/bin/tiger/tiger.rs"

# Tiger2
[[bin]]
name = "tiger2"
path = "src/bin/tiger/tiger2.rs"

# Whirlpool
[[bin]]
name = "whirlpool"
path = "src/bin/whirlpool.rs"
