[package]
name = "sabikui-algs"
version = "0.0.0"
description = "A hash algorithm executable generator for sabikui"

repository.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
blake2 = "0.10.6"
ascon-hash = "0.3.1"
belt-hash = "0.1.1"
sha2 = "0.10.9"
sha3 = "0.10.8"

# Ascon-Hash
[[bin]]
name = "ascon"
path = "src/bin/ascon.rs"

# Belt-Hash
[[bin]]
name = "belt"
path = "src/bin/belt.rs"

# Blake2 Family
[[bin]]
name = "blake2s256"
path = "src/bin/blake2/blake2s256.rs"

[[bin]]
name = "blake2b512"
path = "src/bin/blake2/blake2b512.rs"


# MD5
[[bin]]
name = "md5"
path = "src/bin/md5.rs"

# SHA1
[[bin]]
name = "sha1"
path = "src/bin/sha1.rs"

[[bin]]
name = "sha256"
path = "src/bin/sha256.rs"

[[bin]]
name = "sha512"
path = "src/bin/sha512.rs"

[[bin]]
name = "sha3-256"
path = "src/bin/sha3-256.rs"

[[bin]]
name = "sha3-512"
path = "src/bin/sha3-512.rs"

[[bin]]
name = "blake2b512"
path = "src/bin/blake2b512.rs"
